import 'dotenv/config'
import { MongoClient } from 'mongodb'

const BRANDS = [
  {
    brandId: 'nike',
    aliases: ['justdoit', 'nikesport'],
    displayName: 'Nike',
    tagline: 'Just Do It',
    categories: ['shoes', 'apparel', 'sportswear', 'running', 'training'],
    themeColor: '#F5F5F5',
    accentColor: '#111111',
    logoUrl: null,
    defaultQuery: 'trending sneakers',
    serviceMapping: { shoes: 'products', apparel: 'products' },
    contextPrompt: 'User is shopping Nike. Focus on Nike sportswear, shoes, and athletic apparel. Highlight performance, innovation, and style. Budget: full range.',
    isActive: true,
  },
  {
    brandId: 'adidas',
    aliases: ['adidasoriginals', 'adidassport'],
    displayName: 'Adidas',
    tagline: 'Impossible Is Nothing',
    categories: ['shoes', 'apparel', 'sportswear', 'football', 'running'],
    themeColor: '#FFFFFF',
    accentColor: '#000000',
    logoUrl: null,
    defaultQuery: 'trending adidas',
    serviceMapping: { shoes: 'products', apparel: 'products' },
    contextPrompt: 'User is shopping Adidas. Focus on Adidas sportswear, Originals, and performance gear. Highlight three stripes heritage and modern sport.',
    isActive: true,
  },
  {
    brandId: 'emirates',
    aliases: ['emiratesair', 'ek'],
    displayName: 'Emirates',
    tagline: 'Fly Better',
    categories: ['flights', 'business-class', 'first-class', 'luxury-travel'],
    themeColor: '#C4122F',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'dubai flights',
    serviceMapping: { flights: 'flights', stays: 'stays' },
    contextPrompt: 'User is booking Emirates. Focus on Emirates flights, particularly to/from Dubai and Middle East. Highlight business and first class options. Include hotel and experience recommendations at destination.',
    isActive: true,
  },
  {
    brandId: 'qatar',
    aliases: ['qatarairways', 'qr'],
    displayName: 'Qatar Airways',
    tagline: 'Going Places Together',
    categories: ['flights', 'business-class', 'doha'],
    themeColor: '#5C0632',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'doha flights',
    serviceMapping: { flights: 'flights' },
    contextPrompt: 'User is booking Qatar Airways. Focus on Qatar flights via Doha hub. Highlight QSuite business class and award-winning service.',
    isActive: true,
  },
  {
    brandId: 'gucci',
    aliases: ['guccio', 'gucciofficial'],
    displayName: 'Gucci',
    tagline: 'Quality Is Remembered Long After Price Is Forgotten',
    categories: ['luxury', 'fashion', 'bags', 'shoes', 'accessories'],
    themeColor: '#1B1B1B',
    accentColor: '#C4A55A',
    logoUrl: null,
    defaultQuery: 'gucci bags',
    serviceMapping: { fashion: 'products', accessories: 'products' },
    contextPrompt: 'User is shopping Gucci. Focus on Gucci luxury fashion, bags, shoes, and accessories. Emphasise Italian craftsmanship, GG monogram, and seasonal collections.',
    isActive: true,
  },
  {
    brandId: 'zara',
    aliases: ['zaraofficials', 'inditex-zara'],
    displayName: 'Zara',
    tagline: 'Your Style, Your Story',
    categories: ['fashion', 'clothing', 'accessories', 'fast-fashion'],
    themeColor: '#FFFFFF',
    accentColor: '#1A1A1A',
    logoUrl: null,
    defaultQuery: 'new collection',
    serviceMapping: { fashion: 'products' },
    contextPrompt: 'User is shopping Zara. Focus on Zara fast fashion, seasonal collections, and trend-led clothing. Highlight new arrivals and sale items.',
    isActive: true,
  },
  {
    brandId: 'apple',
    aliases: ['apple-inc', 'appleinc'],
    displayName: 'Apple',
    tagline: 'Think Different',
    categories: ['electronics', 'tech', 'iphone', 'mac', 'ipad'],
    themeColor: '#F5F5F7',
    accentColor: '#1D1D1F',
    logoUrl: null,
    defaultQuery: 'latest apple products',
    serviceMapping: { electronics: 'products', tech: 'products' },
    contextPrompt: 'User is shopping Apple. Focus on Apple products: iPhone, Mac, iPad, Apple Watch, AirPods. Highlight ecosystem integration and latest models.',
    isActive: true,
  },
  {
    brandId: 'hilton',
    aliases: ['hiltonhotels', 'hiltonhonors'],
    displayName: 'Hilton',
    tagline: 'Be Our Guest',
    categories: ['hotels', 'stays', 'luxury-hotels', 'resorts'],
    themeColor: '#002855',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'hilton hotels',
    serviceMapping: { hotels: 'stays', resorts: 'stays' },
    contextPrompt: 'User is booking Hilton. Focus on Hilton Hotels & Resorts properties. Include Waldorf Astoria, Conrad, and DoubleTree options. Highlight Honors points and member benefits.',
    isActive: true,
  },
  {
    brandId: 'marriott',
    aliases: ['marriottbonvoy', 'marriotthotels'],
    displayName: 'Marriott',
    tagline: 'Marriott Bonvoy — Travel Brilliantly',
    categories: ['hotels', 'stays', 'luxury-hotels', 'resorts'],
    themeColor: '#A8192E',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'marriott hotels',
    serviceMapping: { hotels: 'stays' },
    contextPrompt: 'User is booking Marriott. Focus on Marriott Bonvoy portfolio: Ritz-Carlton, W Hotels, Westin, Sheraton. Highlight Bonvoy points and member rates.',
    isActive: true,
  },
  {
    brandId: 'airbnb',
    aliases: ['airbnbstays', 'airbnbhost'],
    displayName: 'Airbnb',
    tagline: 'Belong Anywhere',
    categories: ['stays', 'accommodation', 'vacation-rental', 'unique-stays'],
    themeColor: '#FF5A5F',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'unique stays',
    serviceMapping: { stays: 'stays', experiences: 'experiences' },
    contextPrompt: 'User wants Airbnb-style accommodation. Focus on unique homes, villas, apartments, and local experiences. Highlight host ratings and neighbourhood character.',
    isActive: true,
  },
  {
    brandId: 'uniqlo',
    aliases: ['uniqloglobal', 'fastretailing'],
    displayName: 'Uniqlo',
    tagline: 'Made for All',
    categories: ['fashion', 'basics', 'casual', 'sustainable'],
    themeColor: '#FF0000',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'uniqlo essentials',
    serviceMapping: { fashion: 'products' },
    contextPrompt: 'User is shopping Uniqlo. Focus on Uniqlo basics, LifeWear philosophy, Heattech, AIRism, and seasonal collections. Highlight quality, simplicity, and affordability.',
    isActive: true,
  },
  {
    brandId: 'samsung',
    aliases: ['samsungelectronics', 'samsungglobal'],
    displayName: 'Samsung',
    tagline: "Do What You Can't",
    categories: ['electronics', 'smartphones', 'tvs', 'appliances'],
    themeColor: '#1428A0',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'samsung galaxy',
    serviceMapping: { electronics: 'products' },
    contextPrompt: 'User is shopping Samsung. Focus on Galaxy phones, tablets, TVs, and home appliances. Highlight Galaxy AI features and ecosystem connectivity.',
    isActive: true,
  },
  {
    brandId: 'spotify',
    aliases: ['spotifymusic', 'spotify-streaming'],
    displayName: 'Spotify',
    tagline: 'Music for Everyone',
    categories: ['streaming', 'music', 'podcasts', 'digital-services'],
    themeColor: '#191414',
    accentColor: '#1DB954',
    logoUrl: null,
    defaultQuery: 'spotify premium',
    serviceMapping: { streaming: 'digital_services', subscription: 'digital_services' },
    contextPrompt: 'User wants Spotify. Focus on Spotify Premium plans, family/duo plans, and student discounts. Highlight podcast library and AI DJ.',
    isActive: true,
  },
  {
    brandId: 'uber',
    aliases: ['ubercab', 'uberride'],
    displayName: 'Uber',
    tagline: 'Move the Way You Want',
    categories: ['transport', 'rides', 'food-delivery', 'cars'],
    themeColor: '#000000',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'ride',
    serviceMapping: { rides: 'cars', transport: 'cars' },
    contextPrompt: 'User wants Uber. Focus on Uber ride options (UberX, Comfort, Black), Uber Eats, and Uber One membership. Include car rental via Uber Rent where relevant.',
    isActive: true,
  },
  {
    brandId: 'amazon',
    aliases: ['amazonprime', 'amazonshopping'],
    displayName: 'Amazon',
    tagline: 'Work Hard. Have Fun. Make History.',
    categories: ['shopping', 'products', 'prime', 'electronics', 'books'],
    themeColor: '#FF9900',
    accentColor: '#131921',
    logoUrl: null,
    defaultQuery: 'best sellers',
    serviceMapping: { products: 'products', shopping: 'products' },
    contextPrompt: 'User is shopping Amazon. Focus on Amazon product listings with Prime delivery, customer reviews, and competitive pricing. Highlight Prime exclusives.',
    isActive: true,
  },
  {
    brandId: 'netflix',
    aliases: ['netflixofficial', 'netflixstreaming'],
    displayName: 'Netflix',
    tagline: "See What's Next",
    categories: ['streaming', 'entertainment', 'digital-services'],
    themeColor: '#141414',
    accentColor: '#E50914',
    logoUrl: null,
    defaultQuery: 'netflix plans',
    serviceMapping: { streaming: 'digital_services' },
    contextPrompt: 'User wants Netflix. Focus on Netflix subscription plans, available in their region. Highlight new releases, Netflix Originals, and ad-supported plan options.',
    isActive: true,
  },
  {
    brandId: 'lufthansa',
    aliases: ['lufthansaairlines', 'lh'],
    displayName: 'Lufthansa',
    tagline: 'Non-stop You',
    categories: ['flights', 'business-class', 'europe', 'frankfurt'],
    themeColor: '#05164D',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'frankfurt flights',
    serviceMapping: { flights: 'flights' },
    contextPrompt: 'User is booking Lufthansa. Focus on Lufthansa flights via Frankfurt/Munich hubs. Highlight Business Class and Senator lounge access. Include Star Alliance partner options.',
    isActive: true,
  },
  {
    brandId: 'prada',
    aliases: ['pradaofficial', 'pradagroup'],
    displayName: 'Prada',
    tagline: 'The Privilege of Being',
    categories: ['luxury', 'fashion', 'bags', 'shoes', 'accessories'],
    themeColor: '#1B1B1B',
    accentColor: '#C4A55A',
    logoUrl: null,
    defaultQuery: 'prada bags',
    serviceMapping: { fashion: 'products', luxury: 'products' },
    contextPrompt: 'User is shopping Prada. Focus on Prada luxury fashion, iconic bags (Galleria, Re-Edition), footwear, and accessories. Highlight Italian craftsmanship and contemporary design.',
    isActive: true,
  },
  {
    brandId: 'vogue',
    aliases: ['voguemagazine', 'condenast-vogue'],
    displayName: 'Vogue',
    tagline: 'The Fashion Authority',
    categories: ['fashion', 'beauty', 'luxury', 'lifestyle'],
    themeColor: '#FFFFFF',
    accentColor: '#000000',
    logoUrl: null,
    defaultQuery: 'fashion trends',
    serviceMapping: { fashion: 'products', beauty: 'products' },
    contextPrompt: 'User is inspired by Vogue. Focus on editorial fashion picks, luxury brands, trending styles, and beauty products. Highlight runway-to-retail and editor recommendations.',
    isActive: true,
  },
  {
    brandId: 'booking',
    aliases: ['bookingcom', 'booking-hotels'],
    displayName: 'Booking.com',
    tagline: 'The Place to Book',
    categories: ['hotels', 'stays', 'apartments', 'vacation-rentals'],
    themeColor: '#003580',
    accentColor: '#FFFFFF',
    logoUrl: null,
    defaultQuery: 'hotels',
    serviceMapping: { hotels: 'stays', accommodation: 'stays' },
    contextPrompt: 'User is using Booking.com. Focus on hotels, apartments, and unique accommodations with free cancellation options. Highlight Genius loyalty program benefits.',
    isActive: true,
  },
]

async function main() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI not set')

  const client = new MongoClient(uri)
  await client.connect()
  const db = client.db()

  console.log('Seeding brands...')
  let inserted = 0
  let updated = 0

  for (const brand of BRANDS) {
    const result = await db.collection('brands').updateOne(
      { brandId: brand.brandId },
      { $set: { ...brand, updatedAt: new Date() }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true }
    )
    if (result.upsertedCount > 0) inserted++
    else updated++
  }

  console.log(`Done: ${inserted} inserted, ${updated} updated (${BRANDS.length} total brands)`)
  await client.close()
}

main().catch(err => { console.error(err); process.exit(1) })
